def position_motifs(dna, motif):
    res = []
    for indx in range(len(dna)):
        if dna[indx] == motif[0]:
            if(dna[indx: indx + len(motif)]) == motif:
                res.append(indx + 1)
    return res


if __name__ == '__main__':
    locations = position_motifs("GAAAAGTAACAGGTAACAGGTAACAGGATTGAGTCGGTAACAGGGTAACAGTGTAACAGGTAACAGGTAACAGGTAACAGGCTGTGTAACAGGTACCCAAAGTACATTCGATAGGAATACGCTGTAACAGTCTCGTAACAGGGTAACAGGTGTAACAGCTAGTAACAGGTAACAGCTGTAACAGAAGGGGTAACAGGGCCCAAGTAACAGGTTTTGTAACAGGGTAACAGGTAACAGGGTAACAGCGTAACAGCAAGTAACAGCGTAACAGGGTAACAGGGTAACAGACCGCGTAACAGGTAACAGGGAACGCGTAACAGCTCGTAACAGGGGGGTAACAGAAGGTAACAGCCGTAACAGCGGTAACAGGCAGTAACAGTTCGTAACAGGTAACAGAGGTAACAGCCGTAACAGGTAATTACCTCACTTGTAACAGCCGTAACAGAGGTAACAGAGTAACAGGTAACAGGTAACAGGATGTAACAGGATTGTAACAGGCGTAACAGGGTAGTGGTAACAGTGGCGTAACAGAGCAAAGTAACAGAGCCAAAGTAACAGTGTAACAGTGTAACAGACCAGATGTAACAGCTGTAACAGGTAACAGGGTAACAGGCGGGGGGTAACAGTCCTGTAACAGGTAACAGGTAACAGCTGTAACAGCCGTAACAGCGTGAAACTCCCGCGTAACAGACCGTAACAGTCGCGATGTAACAGGTGTAACAGGTCCGTAACAGGTAACAGCCCGGCCCATAGTAACAGCGGTAACAGAATAGTAACAGGGGTAACAGCGTAT", "GTAACAGGT")
    for location in locations:
        print(location, end=" ")